import { Shield } from "lucide-react";

export default function MetricsInfoCard() {
  const metrics = [
    { title: "RM Score", desc: "Composite performance rating (0-100) based on accuracy, consistency, and game management." },
    { title: "Strictness", desc: "Card frequency and disciplinary approach. Higher values indicate a stricter refereeing style." },
    { title: "Chaos Index", desc: "Match volatility generated by referee decisions — cards, penalties, and contentious calls." },
  ];

  return (
    <div className="mb-6 rounded-[20px] p-5" style={{ background: "rgba(16,185,129,0.04)", border: "1px solid rgba(16,185,129,0.12)" }}>
      <div className="flex items-center gap-2 mb-4">
        <Shield size={16} className="text-emerald-400" />
        <h3 className="font-display text-xl font-black text-white uppercase">Understanding the Metrics</h3>
      </div>
      <div className="grid gap-5 md:grid-cols-3">
        {metrics.map((m) => (
          <div key={m.title}>
            <h4 className="text-sm font-bold text-emerald-400 mb-1">{m.title}</h4>
            <p className="text-xs leading-6 text-slate-500">{m.desc}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
